### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by mawahab** [abenkhadra/spedi#1] opened 2017-04-24 14:30 UTC
I tried disassembling an elf binary and I got a segmentation fault. I have ARM and Thumb mode instructions inside the binary.
How can I easily find out what is causing this segmentation fault error ? I did not find any debug options in command line. How can I debug to find the origin of this error ? Thank you in advance for your reply !

**Comment by abenkhadra** [comment] 2017-04-28 15:27
As discussed offline. It's more probable that the Seg Fault is caused by the ELF reader I'm using. Anyways, I've fixed CMakeLists to make `Spedi` better debuggable. Valgrind can be particularly useful for debugging memory errors like this one.

I shall close this now until more information is available.

**Closed as completed by abenkhadra** 2017-04-28 15:27 UTC

**Comment by mawahab** [comment] 2017-04-28 15:57
Hi Ammar,

Thank you for your help and time. I will look into it this weekend and 
if I have questions, I may bother you again. If I sort out, you will 
know the changes and I will create a pull request. Thanks for closing 
the issue. I opened before contacting you.

Thanks,
Best,
Muhammad
